# Generated by Django 5.2 on 2025-05-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_apiconsumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincode',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
