services:
  back:
    restart: unless-stopped
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file:
      - ./back/.env
    volumes:
      - ./back/media:/app/media
      - /data:/app/data
      - ./logs:/app/logs
    networks:
      - internal
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL 
    cap_add:
      - NET_BIND_SERVICE

  front:
    restart: unless-stopped
    build:
      context: ./front
      dockerfile: Dockerfile
    env_file:
      - ./front/.env
    networks:
      - internal
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL

  caddy:
    restart: unless-stopped
    container_name: caddy
    image: caddy:2.11-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy-config:/config
      - ./caddy-data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./back/media:/peralta/media:ro
      - ./caddy-log:/log
    networks:
      - internal
      - external
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

networks:
  internal:
    internal: true
  external:
    driver: bridge